### ISSUE TITLE
Issues when using fasta files on Windows

### ISSUE THREAD

**Issue by cying111** [GoekeLab/bambu#101]
Using fasta files on Windows throws error message, recommend to replace the fasta file with "BSgenome.Hsapiens.NCBI.GRCh38" will resolve the problem, i.e., set genomeSequence = "BSgenome.Hsapiens.NCBI.GRCh38"

If you still prefer to use fasta, we would recommend to use it on non-Windows platform, as the problem is related to [a reported unsolved bug with getSeq on Windows](https://github.com/Bioconductor/Rsamtools/issues/12)

**Comment by yuukiiwa** [comment]
I'm having problems with using fasta as genomeSequence in bambu on Mac. Here is the error message: 
![Screen Shot 2020-06-06 at 12 03 15 PM](https://user-images.githubusercontent.com/41866052/83935617-c4db1000-a7ed-11ea-9fa1-ebe29f4a9b59.png)

**Comment by yuukiiwa** [comment]
Here is the traceback of the run:
![Screen Shot 2020-06-08 at 11 25 10 AM](https://user-images.githubusercontent.com/41866052/83990013-d30a6700-a97a-11ea-8a71-60bf8c3f15ac.png)

**Comment by cying111** [comment]
> Here is the traceback of the run:
> ![Screen Shot 2020-06-08 at 11 25 10 AM](https://user-images.githubusercontent.com/41866052/83990013-d30a6700-a97a-11ea-8a71-60bf8c3f15ac.png)

I've tested it on Mac and it seems that this error is caused by the bpvec usage in junctionCorrection.R . I've removed this in the latest version.

**Comment by yuukiiwa** [comment]
I have installed the latest version of bambu, and it throws the same error message I got previously. Here is the traceback:
![Screen Shot 2020-06-15 at 10 11 03 PM](https://user-images.githubusercontent.com/41866052/84667888-7f3ce680-af55-11ea-91c8-ee863f1e2bc1.png)

**Comment by Drakyrie** [comment]
For a windows work around using a .fasta, in createJunctionTable() replace 

> genomeSequence <- Rsamtools::FaFile(genomeSequence)

with

> #requires Biostring
> genomeSequence <- readDNAStringSet(genomeSequence)

and move the following code outside and below the else statement

```
if(!all(seqlevels(unlisted_junction_granges) %in% seqlevels(genomeSequence))) {
      message("not all chromosomes present in reference genome sequence, ranges are dropped")
      unlisted_junction_granges <- keepSeqlevels(unlisted_junction_granges,
                                                 value = seqlevels(unlisted_junction_granges)[seqlevels(unlisted_junction_granges) %in% seqlevels(genomeSequence)],
                                                 pruning.mode = 'coarse')
```

The final if statement should look like this at the end.
`  if(is.null(genomeSequence)){
    stop("Reference genome sequence is missing, please provide fasta file or BSgenome name, see available.genomes()")
  }else if(class(genomeSequence) != 'FaFile'){
    if(grepl('.fa',genomeSequence)){
      #genomeSequence <- Rsamtools::FaFile(genomeSequence)
      genomeSequence <- readDNAStringSet(genomeSequence)
    }else {
      if (!suppressWarnings(require(BSgenome, quietly=TRUE)))
        stop("Please install the BSgenome package")
      
      genomeSequence <- BSgenome::getBSgenome(genomeSequence)
      seqlevelsStyle(genomeSequence) <- seqlevelsStyle(unlisted_junction_granges)[1]
    }
    
    if(!all(seqlevels(unlisted_junction_granges) %in% seqlevels(genomeSequence))) {
      message("not all chromosomes present in reference genome sequence, ranges are dropped")
      unlisted_junction_granges <- keepSeqlevels(unlisted_junction_granges,
                                                 value = seqlevels(unlisted_junction_granges)[seqlevels(unlisted_junction_granges) %in% seqlevels(genomeSequence)],
                                                 pruning.mode = 'coarse')
    }
  }
  `

**Comment by cying111** [comment]
Thanks! @Drakyrie , I have updated the code accordingly!
