### ISSUE TITLE
Error when running Bambu

### ISSUE THREAD

**Issue by qhauck16** [GoekeLab/bambu#164]
Hi again, 
I am running into another issue when running bambu. : 
```Start generating read class files
  |                                                                               |   0%Error in seqlevelsStyle(seqlevels(x)) : 
  The style does not have a compatible entry for the species supported by
  Seqname. Please see genomeStyles() for supported species/style
```

I ran:
```bambu(reads = test.bam, annotations = gtf_bambu, genomeSequence = fa.file, extendAnnotations = FALSE)```

The prepareAnnotations worked fine w/the gtf, so I'm not sure what might be causing this error.

Thanks, 
Quinn

**Comment by cying111** [comment]
hi @qhauck16 , thank you for the feedback, may I check with you that are you using a customized gtf/fasta file? The error might be coming from the internal calling of function seqlevelsStyle(), which is default to the know style NCBI and UCSC, so if a customized gtf file is used, it might cause issues. We will fix this in a new version to allow taking in of customized gtf file.

**Comment by cying111** [comment]
Hi @qhauck16. we have allowed customized gtf/fasta file for now. Please check.

**Comment by cying111** [comment]
I will close this issue for now. 

If you have further questions, please post it here: https://support.bioconductor.org/ with tag to `bambu`. Thank you!
