### ISSUE TITLE
Error with BAMs when running Bambu

### ISSUE THREAD

**Issue by M-corre** [GoekeLab/bambu#184]
Hi,
Everything works perfectly until I tried to run the bambu function :

> se <- bambu(reads = files, rcOutDir = file.path(mydir, "bambu_Gencode"), annotations = bambuAnnotations, genome = fa.file, stranded = FALSE, verbose = TRUE, discovery = FALSE)

I then get this error message : 

> Error in S4Vectors:::normarg_names(value, class(x), length(x)) :  attempt to set too many names (1) on IRanges object of length 0

Any suggestions to fix this ?
Thank you very much
Morgane

**Comment by cying111** [comment]
Hi @M-corre, could you provide me the seqlevels information regarding the bam files, bambuAnnotations and fa.file you used?

**Comment by M-corre** [comment]
Hi,
Here you are, it appears not to be optimal....
I tried to re-download the gtf and fasta file.

> seqlevels(bam_files)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"character"’
> seqlevels(bambuAnnotations)
 [1] "chr1"  "chr2"  "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"  "chr9"  "chr10" "chr11" "chr12" "chr13"
[14] "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr20" "chr21" "chr22" "chrX"  "chrY"  "chrM" 
> seqlevels(fa.file)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"character"’

> seqinfo(bambuAnnotations)
Seqinfo object with 25 sequences from an unspecified genome; no seqlengths:
  seqnames seqlengths isCircular genome
  chr1           <NA>       <NA>   <NA>
  chr2           <NA>       <NA>   <NA>
  chr3           <NA>       <NA>   <NA>
  chr4           <NA>       <NA>   <NA>
  chr5           <NA>       <NA>   <NA>
  ...             ...        ...    ...
  chr21          <NA>       <NA>   <NA>
  chr22          <NA>       <NA>   <NA>
  chrX           <NA>       <NA>   <NA>
  chrY           <NA>       <NA>   <NA>
  chrM           <NA>       <NA>   <NA>
> seqinfo(fa.file)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqinfo’ for signature ‘"character"’
> seqinfo(bam_files)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqinfo’ for signature ‘"character"’

> seqlevelsStyle(fa.file)
Error in seqlevelsStyle(fa.file) : 
  The style does not have a compatible entry for the species supported by Seqname. Please see
  genomeStyles() for supported species/style
> seqlevelsStyle(bam_files)
Error in seqlevelsStyle(bam_files) : 
  The style does not have a compatible entry for the species supported by Seqname. Please see
  genomeStyles() for supported species/style
> seqlevelsStyle(bambuAnnotations)
[1] "UCSC"

thanks !!

**Comment by M-corre** [comment]
Downloading the new versions of the genome and annotation didn't change a thing... I don't understand why the fa.file is not recognized though

**Comment by cying111** [comment]
Thanks @M-corre! Is your bam file generated using the provided genome and annotation file? Also, could you show me the message printout before the error message?

**Comment by M-corre** [comment]
Hi, as a matter of fact, I aligned my fastq on the right reference genome (Gencode) but the alignement tool I used (Minimap2) did not offer indexing options, so I did not use the annotation file while generating the BAMs...
Sure, here you are : 
> se <- bambu(reads = files, rcOutDir = file.path(mydir, "Bambu_file"), annotations = bambuAnnotations, genome = fa.file, stranded = FALSE, discovery = FALSE)
Start generating read class files
  |                                                                                                      |   0%Error in S4Vectors:::normarg_names(value, class(x), length(x)) : 
  attempt to set too many names (1) on IRanges object of length 0
Thanks for your help !

**Comment by cying111** [comment]
Thanks! it's still a bit unclear to me where this happens, can I ask you to try this `se <- bambu(reads = files, rcOutDir = file.path(mydir, "Bambu_file"), annotations = bambuAnnotations, genome = fa.file, stranded = FALSE, discovery = FALSE, verbose = TRUE)` and share with me the printout message?

**Comment by M-corre** [comment]
> se <- bambu(reads = files, rcOutDir = file.path(mydir, "Bambu_file"), annotations = bambuAnnotations, genome = fa.file, stranded = FALSE, discovery = FALSE, verbose = TRUE)
[1] 1
Error in S4Vectors:::normarg_names(value, class(x), length(x)) : 
  attempt to set too many names (1) on IRanges object of length 0

**Comment by cying111** [comment]
Hi @M-corre, may I check with you that if your data has no junction covered? If all your alignments are single range with no junction coverage, then this error will show up. As bambu is designed for long read, we would expect the reads to have at least some junction coverage when aligned to genome. Hope this clarifies your questions. 

Thank you.

**Comment by M-corre** [comment]
Hi @cying111 , Thanks for the insight. Sorry for asking, but how can I check that ? My data are Nanopore reads, not much coverage but should be enough...

**Comment by cying111** [comment]
If you are checking from R:
> library(GenomicAlignments)
> a <- grglist(readGAlignments(path_to_your_bam_file))# this is one of the ways you can read in bam file in R 
> table(elementNROWs(a)) # this should give you the number of ranges for each read

**Comment by M-corre** [comment]
Here it is 👍 library(GenomicAlignments)
> a <- grglist(readGAlignments("D:/Bioinformatics/Bambu_Nano/Bam_Gencode/0h_10h/0h_14.bam"))# this is one of the ways you can read in bam file in R
> table(elementNROWS(a))

      1 
2205640 

I feel like my BAMs are the problem...

**Comment by cying111** [comment]
How is your bam file generated? If you are using minimap2, make sure that --splice is specified to allow the minimap2 to recognize the junctions (https://github.com/lh3/minimap2), see below:

> minimap2 -ax splice ref.fa nanopore-cdna.fa > aln.sam        # Nanopore 2D cDNA-seq
> minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam  # Nanopore Direct RNA-seq

**Comment by M-corre** [comment]
I think the best thing to do is to regenrate my Bam files with the proper conditions you gave me... Might take a while though. I'll let you know asap ! Thank you very much for those tips !!

**Comment by M-corre** [comment]
I regenerated my bam files with your parameters and it worked ! Thank you !

**Comment by cying111** [comment]
No problem! I will close this issue then!
