### ISSUE TITLE
Partial and full isoforms

### ISSUE THREAD

**Issue by mei-du** [GoekeLab/bambu#201]
Hi, how does bambu define and/or distinguish between full and partial isoforms? Would the shorter transcripts here be partial? Thanks!
![image](https://user-images.githubusercontent.com/58542302/107707086-73d4d180-6d15-11eb-8ce4-78ae9aa6bafe.png)

**Comment by jonathangoeke** [comment]
Hi @mei-du in principle, all isoforms are considered full, bambu only distinguishes full length and partial reads. I'm not sure though if this answered your question? If you add a bit more context we can provide additional information. We hope to post a preprint soon describing bambu in more detail.
