### ISSUE TITLE
The use of correct junction to exon differences in coordinates in createExonsByReadClass could introduce errors 

### ISSUE THREAD

**Issue by cying111** [GoekeLab/bambu#210]
When trying to run processReads on one of the samples, I found that this step in contructReadClasses might introduce errors for very small exons (1bp exon). 

Before correcting:
[3]       12 49129573-49129574      +
After correcting:
 [3]       12 49129574-49129573      +

Currently this is causing errors when output passed to scoreReadClasses, where unlistIntrons would ignore this exon by giving one less intron, different from number of exons -1 and therefore causing issues to isReadClassCompatible. 

I changed the code in isReadClassCompatible a bit for runs to pass through when this happens.

But I think maybe we should note this point down to see whether changes need to be made for such 1 bp exons.

**Comment by andredsim** [comment]
This was solved quite awhile ago, and I didn't realize there was an issue posted for it.
#05133ca #3a94b32 #6fce152
