### ISSUE TITLE
readID to transcriptID

### ISSUE THREAD

**Issue by enovoa** [GoekeLab/bambu#213]
Hello! Thanks for making this software available. I was wondering if there is some way to obtain the assignments of readIDs to transcriptIDs that are done by bambu (which are then used to get quantifications)? Thanks in advance!

**Comment by cying111** [comment]
Hi @enovoa , to find out the assignment of readIDs to transcriptIDs, you may use this internal function,

`isore.estimateDistanceToAnnotations(seReadClass,    annotationGrangesList, min.exonDistance = 35,    additionalFiltering = FALSE, verbose = FALSE)`

where the seReadClass is the seobject that is saved to rcOutDir, and annotationGrangsList is either the annotations that used or the extended annotation output you got from bambu.

This function performs the assignment and also estimate the distance between read class and annotations. There might be some details need to be figured out. Would you like the assignment of readIDs to transcriptIDs to be one of the features of bambu? We can try to implement this if it is needed. 

Thanks! Let us know if you have other questions!

**Comment by enovoa** [comment]
Thanks @cying111  - we will try this out!
