### ISSUE TITLE
Error when reading in GTF file

### ISSUE THREAD

**Issue by leiendeckerlu** [GoekeLab/bambu#217]
Hi,

When running the following commands:

```
# read in gtf file
gtf.file <- readFromGTF("./data/HPV16_Pave.gtf")
annotation <- prepareAnnotations(gtf.file)
```

I'm getting the following error:

> Error in as.vector(x, mode = "character") : no method for coercing this S4 class to a vector

the GTF file looks like this and according to gffreader is properly formatted:

```
HPV16	protein_coding	CDS	865	2814	.	+	0	gene_id "E1"; transcript_id "E1"; gene_name "E1";
HPV16	protein_coding	CDS	2756	3853	.	+	0	gene_id "E2"; transcript_id "E2"; gene_name "E2";
HPV16	protein_coding	CDS	3850	4101	.	+	0	gene_id "E5_ALPHA"; transcript_id "E5_ALPHA"; gene_name "E5_ALPHA";
HPV16	protein_coding	CDS	104	559	.	+	0	gene_id "E6"; transcript_id "E6"; gene_name "E6";
HPV16	protein_coding	CDS	562	858	.	+	0	gene_id "E7"; transcript_id "E7"; gene_name "E7";
HPV16	protein_coding	CDS	5639	7156	.	+	0	gene_id "L1"; transcript_id "L1"; gene_name "L1";
HPV16	protein_coding	CDS	4237	5658	.	+	0	gene_id "L2"; transcript_id "L2"; gene_name "L2";
HPV16	protein_coding	CDS	865	880	.	+	0	gene_id "E1_E4_splice"; transcript_id "E1_E4_splice"; gene_name "E1_E4_splice";
HPV16	protein_coding	CDS	3358	3620	.	+	2	gene_id "E1_E4_splice"; transcript_id "E1_E4_splice"; gene_name "E1_E4_splice";
HPV16	protein_coding	CDS	104	226	.	+	0	gene_id "E6_star"; transcript_id "E6_star"; gene_name "E6_star";
HPV16	protein_coding	CDS	409	417	.	+	0	gene_id "E6_star"; transcript_id "E6_star"; gene_name "E6_star";
HPV16	protein_coding	CDS	1265	1302	.	+	0	gene_id "E8_E2_splice"; transcript_id "E8_E2_splice"; gene_name "E8_E2_splice";
HPV16	protein_coding	CDS	3358	3853	.	+	1	gene_id "E8_E2_splice"; transcript_id "E8_E2_splice"; gene_name "E8_E2_splice";
```

any idea what's going on here?

Many thanks,
Lukas

**Comment by leiendeckerlu** [comment]
addendum: With 

`annotation <- prepareAnnotations("./data/HPV16_Pave.gtf")`

I get a different error:

> Error in h(simpleError(msg, call)) : error in evaluating the argument 'i' in selecting a method for function '[': argument 2 is not a vector

**Comment by cying111** [comment]
Hi @leiendeckerlu , could I check with you that does your gtf file contain any gene/transcript/exon features, other than CDS? For bambu to run, we assume that the gtf file has to contain at least exon features for it to run, as we need to construct the granges based on this.

**Comment by leiendeckerlu** [comment]
Hi @cying111 , you're right, so far my GTF did not contain any exon features.  Please correct me if I'm wrong, but it is my understanding that replacing "CDS" with "exon" should in theory do the trick in the GTF file as for my genome CDS and exon are identical. However, I still get the very same error.

**Comment by cying111** [comment]
Hi @leiendeckerlu , I tried to test with the sample rows given here, I think it runs through fine with CDS . I am not sure what could be the issue. It would be helpful if you could provide me a test sample of the file you have? I can see whether I can find out what could be wrong. 
![image](https://user-images.githubusercontent.com/25293260/129360570-82284814-03be-4af3-a941-82850415be8f.png)

**Comment by leiendeckerlu** [comment]
Hi @cying111 , you're absolutely right, if I read the gtf directly with prepareAnnotations() it works, going via readFromGTF() does not work, but that's fine for me :) Many thanks for your help!

```
# that does not work
gtf.file <- readFromGTF("./data/HPV16_Pave_Exon.gtf")
annotation <- prepareAnnotations(gtf.file)

# that works
annotation <- prepareAnnotations("./data/HPV16_Pave_Exon.gtf")
annotation
```

**Comment by cying111** [comment]
Hi @leiendeckerlu, I see. `prepareAnnotations` will help to prepare annotations from txdb object or gtf file directly for bambu to use, while` readFromGTF` is a complimentary function that you can use to read the output gtf file from `writeBambuOutput` as grangeslist object after running `bambu `. So applying output from `readFromGTF` to `prepareAnnotations` will not work.
