### ISSUE TITLE
Issue trying to process big BAM file 100+ GB using Bambu.

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#221]
Hello,

I recently ran into a problem when trying to process a big bam file for a sample sequenced using two PromethION flow cells (144G BAM file). I am running it on an AMD cluster node with 16 cores and 480G of RAM.

Here is the the script I am running:

```
#!/usr/bin/Rscript --vanilla

library("bambu")
args <- commandArgs(trailingOnly = TRUE)

sample.bam <- args[1]
fa.file <- args[2]
gtf.file <- args[3]
name <- args[4]

bambuAnnotations <- prepareAnnotations(gtf.file)
se <- bambu(reads = sample.bam, annotations = bambuAnnotations, rcOutDir = "./no_discovery", genome = fa.file, discovery=FALSE, ncore=16)
se_novel <- bambu(reads = sample.bam, annotations = bambuAnnotations, rcOutDir = "./novel", genome = fa.file, ncore=16)
```

Here is the error message:
```
first error: Internal error in `dict_hash_with()`: Dictionary is full.
```

The code produces this error after running for about 2 hours.
I had ran this code before with smaller files (up to 10Gb BAMs) and everything worked fine.

**Comment by cying111** [comment]
Hi @bernardo-heberle , thanks for the feedback, the error looks unfamiliar to me! But I can make a guess that this is probably related to the sample being too large and that has caused some issue during the parallel processing. 
I probably would suggest you to try the following:
1. to decrease the number of cores, say 16 to 8 and see if it works. 
2. if the error persists, then the current version might not be the best solution for very big samples. I would suggest you to try with our development branch bambu-dev-bioc, and see if works. Do note that it might be unstable as we are still actively working on this branch, so please let us know if you encounter any problem and it will be very helpful for us!

**Comment by andredsim** [comment]
Hi @bernando-heberle, If the above solutions don't work another option is to provide a yieldSize argument to Bambu.

e.g 
`se <- bambu(reads = sample.bam, annotations = bambuAnnotations, rcOutDir = "./no_discovery", genome = fa.file, discovery=FALSE, ncore=16, yieldSize = 5000000)`

This will slightly increase the runtime of Bambu but should reduce the total memory usage as it reads in your large BAM file. Please let us know what works for you!

**Comment by bernardo-heberle** [comment]
Thank you for your suggestions!

 I tried decreasing the number of cores as @cying111 suggested and using the yieldSize argument as @andredsim , but neither solution worked.

I will try to use the bambu-dev-bioc branch this week and let you know how it goes.

**Comment by bernardo-heberle** [comment]
Hi @andredsim and @cying111,

The suggested command (shown below) worked like a charm when using the new build (Version 2.0.1).

` bambu(reads = test.bam, annotations = bambuAnnotations, genome = fa.file, lowMemory = TRUE) `

Thank you for the help and for making this awesome tool!
