### ISSUE TITLE
cannot find "prepareAnnotations" function

### ISSUE THREAD

**Issue by alicecsq** [GoekeLab/bambu#223]
Hi,
    Thank you for providing the Bambu tool. I just install the tool recently and ran into an error with the following code 
`library("TxDb.Hsapiens.UCSC.hg38.knownGene")`
`txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene`
`bambuAnnotations <- prepareAnnotations(txdb)`

Error in prepareAnnotations(txdb) : 
  could not find function "prepareAnnotations"

Could you help? Thank you!
Alice

**Comment by cying111** [comment]
Hi @alicecsq , after installing the package, you will need to do `library(bambu)` to  load the package to the wroking session.
