### ISSUE TITLE
bambu novel transcripts gtf

### ISSUE THREAD

**Issue by gahaddad08** [GoekeLab/bambu#224]
Hi there,

My colleague and I had a suggestion regarding the gtf file that bambu spits out using writeBambuOutput. As we understand it, bambu adds new annotations to the already existing gtf that we provide for it in the command. We were wondering if bambu could also generate an output gtf file where only the transcripts generated by bambu are listed. This could also complete the usage scenarios for non-reference cases.

Thank you for your help and attention to this matter!

Thanks,
Gabriela Haddad and Amol Kainth

**Comment by andredsim** [comment]
In BambuManuscriptRevision we have updated the documentation to make it clearer how to output only novel annotations.
For easy access find it below.

If you are only interested in the novel transcripts, one can filter this 'se' object first to remove reference annotations.
```rscript
se.novel = se[mcols(se)$newTxClass != "annotation",]
writeBambuOutput(se.novel, path = "./bambu/")
```
