### ISSUE TITLE
minimap command

### ISSUE THREAD

**Issue by chelauk** [GoekeLab/bambu#232]
Hi, I want to run bambu and thought I should process my data in a similar way to the way you process your example data:

I notice your reference file for minimap2 is Homo_sapiens.GRCh38.dna_sm.primary_assembly-directRNA-32G.mmi  
Could you explain how this was prepared?  
many thanks

**Comment by cying111** [comment]
Hi @chelauk , this is the index file that we prepared for all directRNA samples using this command 
"minimap2 -x splice -uf -k14 -t 5 -I 32G -d ref.mmi ref.fasta" with "-uf" as the directRNA data is stranded. Let me know if you still have questions. Thank you!

**Comment by chelauk** [comment]
Many thanks for your explanation!
