### ISSUE TITLE
Filtering isoforms present at a low level

### ISSUE THREAD

**Issue by imilenkovic** [GoekeLab/bambu#237]
Hello,
I was wondering how exactly I can filter out isoforms that are represented by a very small number of reads? In other words, when I visualize the isoform detection by running `plotBambu(se, type = "annotation", gene_id = "gene_ID")`, I would only like to keep the isoforms that are moderately or highly abundant (since the scale is log2, eg. only isoforms for which the log2 value will be > 3).
I tried min.readFractionByGene = 0.1 but I guess this is not the right way to do it. Thanks in advance!

**Comment by andredsim** [comment]
Hi,
You could filter the se object by the counts assay (or any of the other assays). e.g

filteredSe = se[log(assays(se)$counts,2)<3]
plotBambu( filteredSe, type = "annotation", gene_id = "gene_ID")

Hope this helps

**Comment by imilenkovic** [comment]
Hello,
I get the following error message:

```
> filteredSe = se[log(assays(se)$counts,2)<3]
Error: subscript is a logical vector with out-of-bounds TRUE values
In addition: Warning message:
In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
```

**Comment by andredsim** [comment]
Sorry I missed a ','. Try

filteredSe = se[log(assays(se)$counts,2)<3,]

**Comment by imilenkovic** [comment]
Sorry to keep asking, but even with adding the comma it's still giving the same error.
When I run just `head(log(assays(se)$counts,2)<3)`, this is what is printed:
```
   HRas.bam PMK1.bam PMK2.bam
tx.1     TRUE     TRUE    FALSE
tx.2    FALSE    FALSE    FALSE
tx.3    FALSE    FALSE    FALSE
tx.4    FALSE    FALSE    FALSE
tx.5    FALSE    FALSE    FALSE
tx.6    FALSE    FALSE    FALSE
```
So it's giving a logical result and not subsetting the columns based on numerical values.

**Comment by andredsim** [comment]
Thats because you arn't splicing the se object. Try

head(se[log(assays(se)$counts,2)<3),]

and let me know what that says

**Comment by imilenkovic** [comment]
```

> head(se[log(assays(se)$counts,2)<3),]

Error: unexpected ')' in "head(se[log(assays(se)$counts,2)<3)"

```

**Comment by andredsim** [comment]
Sorry I am not at my work computer so I can't test the line so I am only doing it by eye. This should be right, the final bracket was in the wrong location

head(se[log(assays(se)$counts,2)<3,])

**Comment by imilenkovic** [comment]
No worries!
I tried that too but it gives a similar error:

```
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'head': subscript is a logical vector with out-of-bounds TRUE values
In addition: Warning message:
In NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,  :
  subscript is an array, passing it thru as.vector() first
```

when I just do `head(log(assays(se)$counts)`, it does work and it does perform log2() of all the counts:

 ```
 HRas.bam PMK1.bam PMK2.bam
tx.1 1.590882 1.314476 2.403179
tx.2 7.789662 6.218600 7.261225
tx.3 7.785097 4.543295 7.542213
tx.4 3.416184 3.296414 3.237188
tx.5 5.171314 3.828081 3.510703
tx.6 6.142899 8.241179 7.772359
```

 but for some reason the condition and splicing don't work.

**Comment by andredsim** [comment]
Oh I see, you have multiple samples. Then you need to summarize them first so you have just one logical vector.

head(se[log(rowSums(assays(se)$counts),2)<3,])
or
head(se[log(rowMeans(assays(se)$counts),2)<3,])
depending how you want to do your threshold
I won't be able reply until tomorrow if this doesn't work sorry as it is late here.
Hope this works.

**Comment by imilenkovic** [comment]
Ah I see! This worked, thanks a lot, and I'm really sorry for bothering with this until late hours. Have a good night and thanks! :)

**Comment by imilenkovic** [comment]
Hello,
Is it also possible to filter based on a specific column? Something like (assays(se)$counts)$column1? I understand that counts is one of the assays, but I can't figure out how to call specific columns within the assay, and I would like to filter based on a minimal number of counts in each of the columns (ie. column1 > 3 && column2 > 3).
Thanks!
