### ISSUE TITLE
Visualizing gene annotation on top of reported/discovered isoforms

### ISSUE THREAD

**Issue by imilenkovic** [GoekeLab/bambu#239]
Hello,
I was asking if there is a way to add the gene annotation with all the annotated exons on top of the plot showing all isoforms (annotated and unannotated) that is produced using plotBambu? This way it would be easy to visually compare the detected isoforms to the annotated gene. Thanks!

**Comment by cying111** [comment]
Hi @imilenkovic , unfortunately we don't provide a visualization for gene annotation on top of transcripts for now. We do provide visualization for gene level annotation and expression, but currently this functionality is a bit buggy. We are currently working to fix that bug and let you know once that is fixed maybe.

**Comment by cying111** [comment]
Hi @imilenkovic , we have fixed the bug for visualization of gene level annotation and expression. Below are the codes that you can follow:
`seGene <- transcriptToGeneExpression(se) # se is the output from bambu

plotBambu(seGene, group.variable = NULL,
    type = 'annotation',
    gene_id = gene_id_of_interest, transcript_id = NULL)`

Thank you and let us know if you have further questions!
