### ISSUE TITLE
Is it possible to add other expression estimates to ouput files?

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#245]
Hi,

In the documentation you mention that it is possible to get different expression estimates for each transcript (e.g., "counts", "CPM", "uniqueCounts", "fullLengthCounts", etc...). However when I write the output of the bambu object with the function below: 

`writeBambuOutput(se, path = "./bambu/")`

The output files only contain the counts for each sample. Is it possible to output files with other expression estimates as well? 

Thanks,
Bernardo

**Comment by cying111** [comment]
Hi @bernardo-heberle , thanks for asking for this. Yes, this is doable. I have added this feature in another branch which you can use: https://github.com/GoekeLab/bambu/tree/writeOtherEstiamtesOutput 

In this branch, running 
`writeBambuOutput(se, path = "./bambu/")`

you will see other estimates files in the folder as well.

Hope this has clarified your question. Let us know if there are further queries.

Thank you

**Comment by bernardo-heberle** [comment]
That's great, thank you @cying111,

I really appreciate how helpful you and the rest of the Bambu dev team are.
