### ISSUE TITLE
The usage of the m6anet()

### ISSUE THREAD

**Issue by JintaoL666** [GoekeLab/bambu#252]
Hello, 
I can not express my issue  suffriciently in english, so I write my question in chinese.
我们在对测序数序数据用m6anet做甲基化分析时，使用Nanopolish软件，需要通过guppy识别得到的带甲基化信息的fastq文件，该过程您使用的那个配置文件？我们只找到了dna_r9.4.1_450bps_modbases_5mc_hac.cfg，由于是Direct_RNA seq数据不匹配（U & T）。
另外，您可以分享一下具体的流程代码吗？我们参考一下，您可以发到我的邮箱吗？1451153371@qq.com，非常感谢您，祝您生活愉快。

**Comment by JintaoL666** [comment]
Dear Dr. Chen:

Thank you very much for your valuable helps!  Look forward to hearing from you.

Best Regards，

Jintao Liu.

**Comment by cying111** [comment]
Hi @JintaoL666 , I have replied you through the email. Do let us know if there are furture questions. Btw, I would encourage you to open a github issue in the [m6anet repo](https://github.com/GoekeLab/m6anet/issues) so that Christ could help directly. 

Thank you
