### ISSUE TITLE
Not all chromosomes present in reference annotations. 

### ISSUE THREAD

**Issue by DrOllyGomez** [GoekeLab/bambu#264]
console looks like:

> summarisedexpt <- bambu(reads = bamfiles, rcOutDir = "/home/mike.harbour/Desktop/bambuWorkingDirectory/bambuOut", annotations = bambuAnnotations, genome = fa.file)
Start generating read class files
iteration: 1not all chromosomes present in reference annotations,
            annotations might be incomplete. Please compare objects
            on the same reference

Error: BiocParallel errors
  1 remote errors, element index: 1
  11 unevaluated and other errors
  first remote error: attempt to set too many names (1) on IRanges object of length 0 

Resources:
1. I downloaded  "gencode.v40.annotation.gtf.gz" from site:
http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/
2. I downloaded "GRCh38.p13.genome.fa.gz"  from SAME site. Expecting these to be compatible.

I mapped my fastq's against the genome file above to create bams.
Then in R I issued:
>gtf.file <- "/home/mike.harbour/Resources/release40/gencode.v40.annotation.gtf"
>bambuAnnotations <- prepareAnnotations(gtf.file)
>fa.file <- "/home/mike.harbour/Resources/release40/GRCh38.p13.genome.fa"
>library(Rsamtools)
>bamfiles <- Rsamtools::BamFileList(c("Desktop/bambuWorkingDirectory/barcode01/aligned_reads_bam_BC01.bam", etc etc etc a further 11 bam files
>summarisedexpt <- bambu(reads = bamfiles, rcOutDir = "Desktop/bambuWorkingDirectory/bambuOut", annotations = bambuAnnotations, genome = fa.file)

and got the errors reported above.

Version
-------
> packageVersion("bambu")
[1] ‘2.0.3’

Any advice, comments, fixes most welcome. Thanks in advance!
Mike

**Comment by cying111** [comment]
Hi @DrOllyGomez ,

Based on the error message, it looks like one of the internal objects is unexpectedly empty. The two files that you used also look good to me as they are compatible. May I know which system are you running this on, Windows or Mac?

**Comment by DrOllyGomez** [comment]
Hiya!
I'm using Ubuntu 20, and I'm running bambu from a singularity image that I obtained from the nf-core nanoseq project (I dont run that pipeline (yet), I am using the image with bambu in it as a standalone app, via a shell into the container.)

In case it is relevant, here is some preparatory code I use to make the bams I aligned using the resources I mentioned:

```
minimap2 -ax map-ont -L $fullpathtogenomeindex $fullpathtomasteroutputdirectory/barcode$bcindex/master.fastq > $fullpathtomasteroutputdirectory/barcode$bcindex/mapoutBC$bcindex.txt 2>$fullpathtomasteroutputdirectory/barcode$bcindex/mapchatBC$bcindex.txt
2>&2
cat $fullpathtomasteroutputdirectory/barcode$bcindex/mapoutBC$bcindex.txt | samtools view -bh -F 2308 -q $qvaluetouse | samtools sort -O bam > $fullpathtomasteroutputdirectory/barcode$bcindex/aligned_reads_bam_BC$bcindex.bam 

```
I'm very grateful for your attention in this matter
Best wishes
Mike

**Comment by cying111** [comment]
Hi @DrOllyGomez , thanks for showing the code that you used to map the reads, it is very helpful. It looks to me like the parameter that you are using is for aligning genomic reads not RNA/cDNA reads, which may give you very little aligned reads and later caused the error I believe, to check that, you can run the following code on your bam file:
`samtools flagstat your_bam_file`
You probably will see very little mapped reads

To map RNA/cDNA reads, you should follow this section 

> Map long mRNA/cDNA reads
minimap2 -ax splice:hq -uf ref.fa iso-seq.fq > aln.sam       # PacBio Iso-seq/traditional cDNA
minimap2 -ax splice ref.fa nanopore-cdna.fa > aln.sam        # Nanopore 2D cDNA-seq
minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam  # Nanopore Direct RNA-seq
minimap2 -ax splice --splice-flank=no SIRV.fa SIRV-seq.fa    # mapping against SIRV control
from minimap2 manual page, where the splice parameter will allow splicing in the genomic reads, so the intron sequences will be skipped.

**Comment by DrOllyGomez** [comment]
Closing ticket, operator supplied wrong input.
