### ISSUE TITLE
counts() doesn't work

### ISSUE THREAD

**Issue by yeroslaviz** [GoekeLab/bambu#275]
I can't access the counts of the object. 

The command I use to run bambu is

`bambu(reads = bam.porechopped, annotations = bambuAnnotations, genome = fa.file )
`
and when I try to access the counts I get the following error

```
> counts(se)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘counts’ for signature ‘"RangedSummarizedExperiment"’
```

The only way I can access the `tx` counts is by using this command:

`assays(se)$counts`

any ideas?

thanks

**Comment by cying111** [comment]
Hi @yeroslaviz , as you noticed, the reported se is a `RangedSummarizedExperiment` object, the transcript expression can only be accessed by `assays(se)$counts`, accessing by `counts` would not work. Hope this clarified your question.

**Comment by yeroslaviz** [comment]
thanks for the answer. Yes i have noticed it and was also able to get the counts like you mentioned. I still don't understnad why i have the `RangedSummarizedExperiment` object and not, like stated in the manual just a `SummarizedExperiment`.
Any specific reason for that?

**Comment by cying111** [comment]
Hi @yeroslaviz , sorry for the confusion, I gues that's a typo on our side, we will update the manual. Thank you for pointing this out!
