### ISSUE TITLE
object 'TRUlibrE' not found

### ISSUE THREAD

**Issue by gringer** [GoekeLab/bambu#283]
I've been provided with the following screenshot from a colleague who is trying to use bambu with human nanopore cDNA reads:

<img width="1058" alt="R error output from bambu" src="https://user-images.githubusercontent.com/856314/176844217-21dc6a59-ecde-4d59-819c-5c92c3a47547.png">

Not quite sure what's going on here, yet, unfortunately.

**Comment by jonathangoeke** [comment]
`stranded=TRUE` should fix this, TRUlibrE is not defined, most likely a typo
