### ISSUE TITLE
Output counts grouped by a cell barcode field in BAM file?

### ISSUE THREAD

**Issue by danledinh** [GoekeLab/bambu#301]
Output counts grouped by a cell barcode field in BAM file?

**Comment by andredsim** [comment]
Hi,

Sorry for the late reply. I am not sure exactly what you are asking for but I will do my best to try and answer.

If you already know the read - cell assignment. You can use the trackReads = TRUE option in bambu to produce a read-to-transcript map. This would allow you to map the barcodes from the reads directly to the transcripts. 

Bambu currently doesn't use and cell barcodes during its processing.

If this doesn't answer your question let me know and I can reopen the issue.
