### ISSUE TITLE
error using bambu

### ISSUE THREAD

**Issue by acarmas1** [GoekeLab/bambu#351]
Hello,

I'm trying to use bambu for transcript quantification and discovery.

Therefore, I've used this code to export my data: 

aln.bam <- BamFile("aln_rep2_sorted.bam")
fa.file <- read.fasta(file = "ref.fna")
bambuAnnotations <- prepareAnnotations('ref.gff')

se <- bambu(reads = aln.bam, annotations = bambuAnnotations, genome = fa.file)

but at the end I'm getting this error:

Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'

Maybe can you help me to troubleshoot this problem, I don't think I'm importing my data correctly. Therefore, bambu cannot read my files properly. 

I'm looking forward to hearing from you,

Thank you

**Comment by andredsim** [comment]
Hi,

Just pass the paths to the files into bambu, bambu handles the import itself. 

```
aln.bam <- "aln_rep2_sorted.bam"
fa.file <-  "ref.fna"
bambuAnnotations <- prepareAnnotations('ref.gff')

se <- bambu(reads = aln.bam, annotations = bambuAnnotations, genome = fa.file)
```

Hope this helps.
