### ISSUE TITLE
Bambu discovers "new genes" on the same strand and overlapping known gene coordinates of given annotation

### ISSUE THREAD

**Issue by bernardo-heberle** [GoekeLab/bambu#356]
Hello,

Three out of the 68 transcripts discovered in new genes reported by Bambu are overlapping annotated gene bodies on the same strand. Is this expected behavior or some kind of bug? It feels like they should be reported as new transcripts for known genes given the overlap.

Here is a screenshot of the coordinates for the new transcripts from new genes and the coordinates of the genes they overlap.
![Screenshot 2023-02-09 120206](https://user-images.githubusercontent.com/81333350/217885305-182842c0-2688-419b-90de-3be0034aa2eb.jpg)

I wonder if this happens because those genes do not have any transcript coordinates overlapping the new transcript even though the gene entry from the GTF file overlaps the new transcript?

PS: The annotation used to retrieve the gene coordinates is the same that was given to Bambu for the analyses.

**Comment by andredsim** [comment]
Hi there,

To be able to answer this fully it would be great if you could include a picture of the ranges of the transcripts from these overlapping genes.

What I can tell you is that in Bambu assigns new genes based on overlapping exon regions. Therefore your hypothesis is correct, and even if an exon falls into the coordinates bound by other gene, if it does not overlap with an exon from that gene it will not be assigned to that gene. We do this to prevent spurious fusing of novel and known gene models. We would be happy to hear any other perspectives on how we could define genes.
