### ISSUE TITLE
how to find the bambu assigned transcript of aligned reads

### ISSUE THREAD

**Issue by icanccwhite** [GoekeLab/bambu#357]
Hi,
   where could I find the details about assigned reads for quantification? 
such as assigned transcript in the annotation of aligned reads

**Comment by icanccwhite** [comment]
> se <- bambu(reads = test.bam, annotations = annotations, genome = fa.file, discovery = FALSE, trackReads = TRUE)
Error in bambu(reads = test.bam, annotations = annotations, genome = fa.file,  :
  unused argument (trackReads = TRUE)
> se <- bambu(reads = test.bam, annotations = annotations, genome = fa.file, discovery = FALSE)   Start generating read class files
  |                                                                      |   0%


no idea about the assigned results

**Comment by cying111** [comment]
Hi @icanccwhite , the error seems to suggest trackReads is not a valid argument, which shouldn't be the case. Which bambu version are you using?

**Comment by icanccwhite** [comment]
Hi @cying111, 
I have changed to version 3.0.6. trackReads works.
 How to save the output data frame "metadata(se)$readToTranscriptMaps[[1]]" directly into a file with bambu?? it's a tibble with list cols in it.

**Comment by icanccwhite** [comment]
> Hi @cying111, I have changed to version 3.0.6. trackReads works. How to save the output data frame "metadata(se)$readToTranscriptMaps[[1]]" directly into a file with bambu?? it's a tibble with list cols in it.

I solved it with multi rows :)

**Comment by shizhuoxing** [comment]
Hi @icanccwhite, could you please share the code of your output trackReads to the file? Thank you!

**Comment by icanccwhite** [comment]
hi @shizhuoxing, I sill share. could you email me later? xyzh@biomed.au.dk

**Comment by icanccwhite** [comment]
> Hi @icanccwhite, could you please share the code of your output trackReads to the file? Thank you!

hi @shizhuoxing, I will share. could you email me later? [xyzh@biomed.au.dk](mailto:xyzh@biomed.au.dk)
