### ISSUE TITLE
Following up BiocParallel errors in #340

### ISSUE THREAD

**Issue by seongwoohan** [GoekeLab/bambu#361]
Hi, I have a similar issue in #340 that I can't solve. I converted fastq to bam file using the below commands and get the screenshot error. 

`./minimap2 -t 8 -ax splice /data/long_read/paper_ref/hg38.fa /data/long_read/for_seong/JH141_RW0588_051220_LiveGuppy.fastq -o /data/long_read/for_seong/JH141_RW0588_051220_LiveGuppy.sam`

`samtools view -@ 8 -Sb -o /data/long_read/for_seong/JH141_RW0588_051220_LiveGuppy.bam /data/long_read/for_seong/JH141_RW0588_051220_LiveGuppy.sam`

![image](https://user-images.githubusercontent.com/19489536/227576928-9be5dea1-e17f-4ce1-aac7-658f530e5199.png)

Using "verbose = True" would make the program run, but I can't save the output files even though I have sparseMatrixStats and DelayedMatrixStats. Let me know if you can help with this.

![image](https://user-images.githubusercontent.com/19489536/227609504-da4a6ba5-8dd4-47c1-9729-0477b27f561e.png)
<img width="970" alt="image" src="https://user-images.githubusercontent.com/19489536/227609610-348157ba-6830-4837-87c7-26fee16501a1.png">

Also, one side note, if I subsample from that fastq file into a smaller file and convert it to bam file, the program works, which I do not understand why.

**Comment by cying111** [comment]
Hi @seongwoohan , it looks to me the error happens during quantification. Could you show me the screenshot of error message if you do it with `verbose = TRUE` and `quant = TRUE`?

**Comment by seongwoohan** [comment]
Hi, bambu gives an extended gtf file (I + II + III) including the annotation, but what I want to get is the gtf file (II + III) which is only constructed by bambu. If I understand correctly, to do that, I need to set quant = False like the command I gave above. Is there a way to only extract II + III after doing quant = True? Shall I do discovery = False, verbose = True, quant = True, and filter the output with constructedAnnotations = se[assays(se)$fullLengthCounts > 0] ?

![image](https://user-images.githubusercontent.com/19489536/227829959-a804284f-350a-44ef-ad43-e49f78c2b801.png)

**Comment by andredsim** [comment]
Hi Seong,

To filter using fullLengthCounts you need to set Quantification = TRUE, if you want to also include novel transcripts (II) you need to set discovery = TRUE. 
Therefore running it exactly how you ran it in the email you sent me is fine (just turn verbose == TRUE so that we can see what is happening when you are running it on the full set). By default discovery and quant are = TRUE.
![image](https://user-images.githubusercontent.com/17838991/227832386-32ccb0b2-1965-4d1d-b030-ba80f98c40f6.png)

**Comment by seongwoohan** [comment]
Here is the error message. It's the same with the error messages above.

![Screenshot 2023-03-27 at 1 51 08 PM](https://user-images.githubusercontent.com/19489536/228025029-f3cbd38b-59b3-49bb-81b9-0e49559eb88e.png)

**Comment by seongwoohan** [comment]
The next command line I tried was the following command, but can't save the output, which is the same issue I had above with Verbose = True.

`se_andrei_pre <- bambu(reads = andrei_pre.bam, annotations = bambuAnnotations, genome = fa.file, quant = FALSE, discovery = FALSE, verbose = TRUE)`

`writeBambuOutput(se_andrei_pre, path = "/home/seong/lr_paper/lr_output/andrei/pre_bambu")`

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/19489536/228083239-c1ba6a2d-ab0f-4dbc-8960-6f5687dfe1f4.png">

**Comment by cying111** [comment]
Hi @seongwoohan , thank you for sharing the error message:

for the error message that you saw when have discovery and quant set to TRUE by default, I think I know where the error happens. But for me to debug what is the issue, could you share your bam file, annotation file, as well as fasta file so that I can understand the problem better? You can send the files to my email chen_ying@gis.a-star.edu.sg

for the second error of not able to save the output when quant is set to FALSE, it's because `writeBambuOutput` is designed to take in the final output when quant is set to TRUE. When quant is set to FALSE, you should use `writeToGTF` function to obtain the output gtf file. 

Hope this clarifies your doubts!

**Comment by seongwoohan** [comment]
Hi @cying111, I am afraid I can't share the dataset since it's not a public dataset, but I think we can still work on it without sharing it. What I want from the bam file is basically the gtf output that only bambu gives, which corresponds to II + III on the venn diagram above.

To do so, the following command gives II + III, which I want. Could you confirm this? 

`se_andrei_pre <- bambu(reads = andrei_pre.bam, annotations = bambuAnnotations, genome = fa.file, quant = FALSE, discovery = FALSE, verbose = TRUE)`

For now, I just want to save this output into a gtf file, but I still couldn't save the output file with `writeToGTF` like the below screenshot. Could you help me save this file into a gtf file, please? At least, I can see "se_andrei_pre" exists as you can see in the screenshot.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/19489536/228109722-2015b0e8-1567-4c84-a480-54e4e2f677f7.png">

**Comment by cying111** [comment]
Hi @seongwoohan , no worries. Please see below for the commands that you should follow to get the filtered annotations and also write it into a gtf file
 

 to obtain the grangeslist for the reported annotations, this step is necessary as the reported output is a list of grangeslist object
> se_andrei_pre <- se_andrei_pre[[1]] 
> 
 to filter out the I and only use II + III, you can try to use the following two methods
 method 1
> se_andrei_pre_filtered <- se_andrei_pre[which(rowData(se_andrei_pre)$readCount >0)]

 method 2
> se_andrei_pre_filtered <- se_andrei_pre[which(!is.na(rowData(se_andrei_pre)$NDR))] 


to write the output
> writeToGTF(se_andrei_pre, path = "/home/seong/lr_paper/lr_output/andrei/pre_bambu")
>

**Comment by seongwoohan** [comment]
Hi @cying111 , thanks for being responsive and helping! I am not sure if writeToGTF can be saved as you suggested. Apologize for bugging you, but could you point out what I am missing?

<img width="925" alt="image" src="https://user-images.githubusercontent.com/19489536/228119952-910dc525-79ce-4ed2-b38e-4513985410bf.png">

**Comment by cying111** [comment]
sorry, I copied wrongly. The command for saving it should be this:
`writeToGTF(se_andrei_pre_filtered, file = "/home/seong/lr_paper/lr_output/andrei/pre_bambu/output.gtf")`

by the way, I noticed that you turned off the discovery. Please turn on the discovery to obtain se_andrei_pre and if you do that, you can ignore this step
`se_andrei_pre <- se_andrei_pre[[1]]`

**Comment by seongwoohan** [comment]
Hmmm, shall I run from the beginning? I am not sure why it's not giving the right output 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/19489536/228120953-921d3b64-2e17-483e-b3d7-03a7631fb600.png">

**Comment by cying111** [comment]
yes, you will need to run from beginning with discovery on and quant off, and then do the filtering step and write to gtf step.

**Comment by seongwoohan** [comment]
Oh, since you just updated your comment, let me run everything from the beginning. Could you check if all of my commands are correct?

`se_andrei_pre <- bambu(reads = andrei_pre.bam, annotations = bambuAnnotations, genome = fa.file, quant = FALSE, discovery = TRUE, verbose = TRUE)`

`se_andrei_pre_filtered <- se_andrei_pre[which(rowData(se_andrei_pre)$readCount >0)]`

`writeToGTF(se_andrei_pre_filtered, file = "/home/seong/lr_paper/lr_output/andrei/pre_bambu/output.gtf")`

**Comment by seongwoohan** [comment]
It took some time to run the first command, but hmm.. there is another error form the second command (the first red box). I tried your alternative in the second box as well.

Could you give me suggestions in this case? Thanks for helping @cying111 

<img width="915" alt="image" src="https://user-images.githubusercontent.com/19489536/228129154-c766f2bb-a580-4d55-933b-2026723ff99e.png">

**Comment by cying111** [comment]
oh ok, I know where the error comes from, can you show me the output of this command first:

> head(mcols(se_andrei_pre),1)


and then try these two commands instead:

> se_andrei_pre_filtered <- se_andrei_pre[which(mcols(se_andrei_pre)$readCount >0)]
> se_andrei_pre_filtered <- se_andrei_pre[which(!is.na(mcols(se_andrei_pre)$NDR))]
>

**Comment by seongwoohan** [comment]
I am re-running bambu, so I will get back to you with the screenshot for the first command soon. Since I am in America Eastern Time Zone, I am trying to stick to your timeline! Thanks for being cooperative! 

By the way, for the two commands you provided, don't I just have to use either one of them, not all two?

**Comment by cying111** [comment]
No problems, thank you for using bambu!

Yes, for the filtering commands, either one should work, let us know if they provide different results though!

**Comment by seongwoohan** [comment]
Here is what I get for the result, and both commands give the same information, thanks!

<img width="919" alt="image" src="https://user-images.githubusercontent.com/19489536/228145348-d73e35bb-390c-43b0-8ba7-afe912836355.png">

But, the filtering command gives too much filtering. Let me explain my experiment. I have a dataset, and I want to run this same dataset itself with bambu and its subsampled version with bambu as well. You can imagine two gtf files (II+III) that have the original dataset and the subsampled dataset. Obviously, the subsampled one would have a small amount of gtf because I randomly took out a few reads from the bam file. I used the below three commands with the subsampled data, and it worked. This gives about 30 GB. If I give the original data, you can imagine that its filtered (II+III) gtf file should have more than 30 GB because it's the original dataset. However, your filtering suggestion gives only 4GB, which clearly doesn't make sense. To do a fair comparison, I would like to use the command below to get the filtered (II+III) gtf file as I did for the subsampled dataset, but as you can see in this thread, it did not work.

`se_andrei_post <- bambu(reads = andrei_post.bam, annotations = bambuAnnotations, genome = fa.file)`
`constructedAnnotations_andrei_post = se_andrei_post[assays(se_andrei_post)$fullLengthCounts > 0]`
`writeBambuOutput(constructedAnnotations_andrei_post, path = "/home/seong/lr_paper/lr_output/andrei/post_bambu")`

I am not sure if this is tricky from your side, but let me know if you can help me with this. Or, is the filtering `se_andrei_pre_filtered <- se_andrei_pre[which(mcols(se_andrei_pre)$readCount >0)] `you suggested is incorrect? It's different from the following. This is what Andrei suggested before. 

`constructedAnnotations_andrei_post = se_andrei_post[assays(se_andrei_post)$fullLengthCounts > 0]`

**Comment by cying111** [comment]
Hi @seongwoohan 

to be able to use what Andre has suggested, you would need to turn the quant mode on. However, we saw the error that you shared before and it is very difficult for us to understand what is the issue there without the data. It would be good if you could share us a sample data that also give the same error, then we can help you to see whether it give similar or different results.
