### ISSUE TITLE
BiocParallel errors when using lowMemory = TRUE

### ISSUE THREAD

**Issue by zhenLiuXplr** [GoekeLab/bambu#365]
Hi

I was using bambu for nanopore quantification these days and it is really a good tool. But I found that I cannot use `lowMemory = TRUE` param in bambu, which will the following error:
```
Error: BiocParallel errors
  0 remote errors, element index: 
  28 unevaluated and other errors
  first remote error:
```

However when I use `lowMemory = FALSE`, I can successfully run my data. I want to know why this happen, beacuse I have another really large dataset to run and I have to use  `lowMemory = TRUE`. 

Thanks!

**Comment by andredsim** [comment]
Hi,

Thanks for reporting this. A few days ago we made a fix to the lowMemory mode and have merged it into the devel branch. Potentially this might resolve this issue, which occurred if there were scaffolds with no reads aligned to it.  Could you try update bambu and see if this resolves this problem. If you still encounter the same error could you please run bambu with verbose = TRUE and post the full output so I can better diagnose the issue. 

Kind Regards,
Andre Sim

**Comment by zhenLiuXplr** [comment]
Thanks Andredsim! I try the bambu 3.1.7 on devel branch. Problem solved!
