### ISSUE TITLE
Error with constructedAnnotations

### ISSUE THREAD

**Issue by kainth-amoldeep** [GoekeLab/bambu#374]
Hi, I am trying to use Bambu to test transcript discovery. For that, I want transcripts that are assembled by Bambu (novel and known) rather than the the entire set of transcripts from the reference. As you suggested in other posts, I tried `constructedAnnotations = se[assays(se)$fullLengthCounts > 0]`. While trying to output it to a file using `writeBambuOutput(constructedAnnotations, path = "path/to/folder")`, it gave me an error: 

> Error: subscript contains invalid names.

However, it did create a folder with the following items: 
**counts_transcript.txt
CPM_transcript.txt
extended_annotations.gtf
fullLengthCounts_transcript.txt
uniqueCounts_transcript.txt**
My impression was that I would get a gtf file for constructedAnnotations. Am I missing something here? Thanks

**Comment by andredsim** [comment]
Hi and thanks for testing Bambu.

Could you check extended_Annotations.gtf? After applying the fullLengthCounts filter that should remove the non-novel and known transcripts solely found in the annotations and they shouldn't be in that gtf file even though it is called extended annotations (the output function is unaware of the filter applied so it keeps the original output file name).

In an upcoming update to Bambu we hope to output both the bambu assembled transcripts in addition to the extended annotations as separate files which should make this process more user friendly as the filter will not need to be manually applied.

**Comment by andredsim** [comment]
Since we have not heard back I hope this solved you issue and will close it for now. If it hasn't let us know please write back with a detailed description of what is occurring and preferentially a reproducible example and we can reopen it.
