### ISSUE TITLE
Including bambu annotation/GRanges for DEXSeq

### ISSUE THREAD

**Issue by rugilemat** [GoekeLab/bambu#391]
Hi,

I've been trying to run DEXSeq based on bambu output:

```
dxd <- DEXSeqDataSet(countData = round(assays(se.multi)$counts), sampleData = as.data.frame(colData(se.multi)),
    design = ~sample + exon + condition:exon, featureID = rowData(se.multi)$TXNAME,
    groupID = rowData(se.multi)$GENEID)
dxr <- DEXSeq(dxd)
```

And while I do get DEXSeq output, I am unable to use their plotting functions to visualise differential exon usage as genomic data (coordinates, strand, length etc) is missing. I tried some ways to include GRanges from bambu produced se.multi in DEXSeq setup but I can't seem to get it to work.

I'm just wondering if there's a way to include bambu generated gtf annotations or GRanges into DEXSeq or do I need to prep annotations for DEXSeq separately and then add that in with bambu counts.

Any help would be great and thanks for this tool!

**Comment by cying111** [comment]
Hi @rugilemat , thanks for using Bambu and submitting your feedback. Bambu currently outputs isoform and gene expression, so applying Bambu output to get differential exon usage would be difficult. Instead you can use Bambu output for differential transcript usage detection, to perform this analysis, we recommend you to follow this tutorial (https://www.bioconductor.org/packages/release/workflows/vignettes/rnaseqDTU/inst/doc/rnaseqDTU.html#drimseq) to prepare your dataset and get it work for DTU detection.

Thank you and let me know if you require additional help.
Ying
