### ISSUE TITLE
bambu command not recognized

### ISSUE THREAD

**Issue by dvirdi01** [GoekeLab/bambu#396]
I cloned the github repo in my conda environment. I tried cd'ing into bambu flder that it created and I wrote bambu --version to see if it works or not. It said command not recognized. I also tried doing 

```
test.bam <- system.file("extdata", "SGNex_A549_directRNA_replicate5_run1_chr9_1_1000000.bam", package = "bambu")
``` 
but it said-     bash: syntax error near unexpected token `('

Am I running the commands wrong?

**Comment by andredsim** [comment]
Hi,

Bambu is an R package. It needs to be run within R or as an Rscript. All the commands in the read me need to be run in an R environment and not the console.

Either open Rstudio or open R in the console with `R` and follow the steps.

First you need to install Bambu in R as detailed in the read me (https://github.com/GoekeLab/bambu#readme)

Let me know if you have any problems with this.

**Comment by dvirdi01** [comment]
I opened a jupyter notebook for R and wrote the Biocmanager command and it showed this: 

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.r-project.org/

Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)

Installing package(s) 'bambu'

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

-----------------------------------------------
I also checked to see if bambu is installed by doing system.file(package='bambu') and it gives me the path where it is installed

I tried running the test example but I get this: 
Error in prepareAnnotations(gtf.file): could not find function "prepareAnnotations"
Traceback:

**Comment by andredsim** [comment]
Now that you have installed bambu in R, you need to load the library at the start of each R session with `library(bambu)`. After that try preapreAnnotations again and let me know if you still get the same error

**Comment by andredsim** [comment]
Since we have not heard back I hope this solved you issue and will close it for now. If it hasn't let us know please write back with a detailed description of what is occurring and preferentially a reproducible example and we can reopen it.
