### ISSUE TITLE
The same transcript with different counts in counts_transcript.txt

### ISSUE THREAD

**Issue by thegreatFANG** [GoekeLab/bambu#410]
Hi there,

Thanks for creating this great tool.
When I followed the test and ran Bambu with my own data, I got the following  results.
![QQ图片20240110183954](https://github.com/GoekeLab/bambu/assets/109190516/f088b162-58fd-4f54-a956-9c703dcf8cd0)
I am wondering about how this happened and how to fix it.

Thanks again!
fang

**Comment by thegreatFANG** [comment]
And here is the code.
`options(BIOCONDUCTOR_CONFIG_FILE = "/data/home/zyfang/config.yaml")
library(bambu)
fa.file = "/data/home/zyfang/Data/fa/GRCh38_full_analysis_set_plus_decoy_hla.fa"
gtf.file = "/data/home/zyfang/Data/gtf/hg38.annot.gtf"
samples.bam = "/data/home/zyfang/Data/bam/RY01.chr22.bam"
se = bambu(reads=samples.bam,annotations=gtf.file,genome=fa.file)
writeBambuOutput(se,path="/data/home/zyfang/Data/output_chr22")
q()
`

**Comment by thegreatFANG** [comment]
And here is the code.
```
options(BIOCONDUCTOR_CONFIG_FILE = "/data/home/zyfang/config.yaml")
library(bambu)
fa.file = "/data/home/zyfang/Data/fa/GRCh38_full_analysis_set_plus_decoy_hla.fa"
gtf.file = "/data/home/zyfang/Data/gtf/hg38.annot.gtf"
samples.bam = "/data/home/zyfang/Data/bam/RY01.chr22.bam"
se = bambu(reads=samples.bam,annotations=gtf.file,genome=fa.file)
writeBambuOutput(se,path="/data/home/zyfang/Data/output_chr22")
q()
```

**Comment by andredsim** [comment]
Hi, 

This is a strange output. Below I have attached what should be expected. From what I can gather from your image I believe that the transcripts highlighted in the read boxes are actually different transcripts, but for some reason the ENST transcript id has been incorrectly appended to the gene id. You could confirm this by looking at the output gtf file for these transcripts to see if they have different coordinates. 

If you don't find a case in this output where the gene id is the same but the ENST transcript id is different than it is likely this is just a superficial issue and you can remove the ENST transcript id and the counts will be fine. However if there are cases where there are two transcripts with the same gene id but different ENST transcript id then I would be worried the quantification is impacted.

As to why this has occurred is puzzling. Would you be able to upload some of the lines from the gtf file you used? 
And the output from the following:
```
library(bambu)
gtf.file = "/data/home/zyfang/Data/gtf/hg38.annot.gtf"
annotations = prepareAnnotations(gtf.file)
print(mcols(annotations))
```

![image](https://github.com/GoekeLab/bambu/assets/17838991/68da3fee-6e9c-445e-98f7-7dfe65f7c8fb)

Kind Regards,
Andre Sim

**Comment by thegreatFANG** [comment]
> Hi,
> 
> This is a strange output. Below I have attached what should be expected. From what I can gather from your image I believe that the transcripts highlighted in the read boxes are actually different transcripts, but for some reason the ENST transcript id has been incorrectly appended to the gene id. You could confirm this by looking at the output gtf file for these transcripts to see if they have different coordinates.
> 
> If you don't find a case in this output where the gene id is the same but the ENST transcript id is different than it is likely this is just a superficial issue and you can remove the ENST transcript id and the counts will be fine. However if there are cases where there are two transcripts with the same gene id but different ENST transcript id then I would be worried the quantification is impacted.
> 
> As to why this has occurred is puzzling. Would you be able to upload some of the lines from the gtf file you used? And the output from the following:
> 
> ```
> library(bambu)
> gtf.file = "/data/home/zyfang/Data/gtf/hg38.annot.gtf"
> annotations = prepareAnnotations(gtf.file)
> print(mcols(annotations))
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/17838991/295758748-68da3fee-6e9c-445e-98f7-7dfe65f7c8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTI4MjgsIm5iZiI6MTcwNTQxMjUyOCwicGF0aCI6Ii8xNzgzODk5MS8yOTU3NTg3NDgtNjhkYTNmZWUtNmU5Yy00NDVlLTk4ZjctN2RmZTY1ZjdjOGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MWNjNmRkYmE0MWQ1NGJjNGRjOGMwMDdjYTc5ODBkY2Q0MDkzMWY5MjdiNzQ5YTNmMGU1MDhhZWZhNDk1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nW_i89IVZU7EtOvbjWC-owsTvN8ra_n_eBfFQOYSTNs)
> 
> Kind Regards, Andre Sim

Thank you for your reply. Based on the information you provided, I have determined that it is my gtf file that caused the issue. My gtf file was converted from a gff3 file, but due to some reasons, the "gene" is missing from this gtf file. When I tested using a correct gtf file, I obtained the correct results.
Thanks again,
fang
