### ISSUE TITLE
Make novel GTF from single cell data using bambu

### ISSUE THREAD

**Issue by hyeon9** [GoekeLab/bambu#436]
Thank you for your highly intuitive and accurate tool!

Recently, I plan to apply Bambu to my single cell RNA sequencing data to get transcriptome information.
So, as I think, it is possible to construct transcriptome based on my merged bam and retain only transcripts with non-zero expression in extended gtf file.
I'm wondering whether this approach makes sense.

Thank you,
Hyeongu

**Comment by andredsim** [comment]
Hi Hyeongu,

Yes it is possible to use single cell data with the current version of bambu if your only goal is to make a novel GTF. As you said, you want to use the merged bam and if you want to remove transcripts where you didn't find any full-length support you can filter out those with non-zero full length counts. 

We are planning to release a single-cell capable version of bambu soon but it is currently in the beta phase at the moment.

Kind Regards,
Andre Sim
