### ISSUE TITLE
Best minimap2 parameters for use with bambu

### ISSUE THREAD

**Issue by rob-p** [GoekeLab/bambu#442]
Hi Bambu team,

  Thanks for the great software!  We (@zzare-umd, @NPSDC and I) were curious if there are any particular parameters you suggest when aligning with `minimap2` prior to `bambu`.  We saw that you may want to pass `-uf` when aligning direct RNA data (https://github.com/GoekeLab/bambu/issues/232), but does it ever make sense to modify the default `-N` or `-p` parameters? Will `bambu` consider *genomic* multimapping reads if equally-good alignments exist?

Thanks!
Rob, Zahra, and Noor

**Comment by cying111** [comment]
Hi @rob-p, @zzare-umd, @NPSDC,

Thank you for your kind words! We're glad that you like the software. Currently, Bambu relies on minimap2 to choose among equally good alignments by filtering out secondary alignments. Therefore, the parameters `-N` and `-p` are expected to have no impact on the results, as all secondary alignments will be filtered out.

Hope this clarifies your question!
Thank you and all the best,
Warm regards,
Ying

**Comment by rob-p** [comment]
Hi @cying111,

  Yes; this helps a lot.  Thanks for the quick response and congrats again on the nice tool!

Best,
Rob

**Comment by llryab01** [comment]
Dear Bambu team, 
I am using Oxford Nanopore long-read RNA-seq data for a transcript-level analysis. I have successfully aligned my reads to the reference genome using minimap2. For downstream isoform discovery and quantification with Bambu, I am trying to determine if I should pre-filter my BAM file based on MAPQ scores (e.g., keeping only uniquely mapped reads with MAPQ ≥ 7) or simply provide the unfiltered BAM file directly.

Specifically, my concerns are:

Does pre-filtering reads based on MAPQ improve the accuracy of transcript discovery and quantification, or does it risk removing genuine reads that could help identify low-abundance or novel isoforms?

Are there any specific minimap2 parameters (e.g., -N, -p) that should be adjusted to optimize the BAM file for Bambu, particularly regarding multi-mapping reads?

I understand that Bambu internally filters out secondary alignments (as noted in a previous issue), but I am unsure about the effect of pre-filtering at the BAM level before running Bambu.

Thank you for your guidance and for developing this valuable tool.
Regards, Lidia
